//
//  RepoListInterfaces.swift
//  SadaPayDemo
//
//  Created by Muhammad Haseeb Siddiqui on 6/20/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol RepoListWireframeInterface: WireframeInterface {
}

protocol RepoListViewInterface: ViewInterface {
}

protocol RepoListPresenterInterface: PresenterInterface {
}

protocol RepoListInteractorInterface: InteractorInterface {
}
