//
//  RepoListPresenter.swift
//  SadaPayDemo
//
//  Created by Muhammad Haseeb Siddiqui on 6/20/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class RepoListPresenter {

    // MARK: - Private properties -

    private unowned let view: RepoListViewInterface
    private let interactor: RepoListInteractorInterface
    private let wireframe: RepoListWireframeInterface

    // MARK: - Lifecycle -

    init(
        view: RepoListViewInterface,
        interactor: RepoListInteractorInterface,
        wireframe: RepoListWireframeInterface
    ) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
    }
}

// MARK: - Extensions -

extension RepoListPresenter: RepoListPresenterInterfaceOutput {
    
    func presentListOfRepos(_ model: APIRepoListModel) {
        let listOfRepos = model.items?.map({RepoListItemViewModel(model: $0)}) ?? []
        view.displayListOfRepos(listOfRepos)
    }
}


extension RepoListPresenter: RepoListPresenterInterfaceInput {

    func viewLoaded() {
        interactor.getRepositories()
    }

}
