//
//  RepoListInterfaces.swift
//  SadaPayDemo
//
//  Created by Muhammad Haseeb Siddiqui on 6/20/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol RepoListWireframeInterface: WireframeInterface {
}

protocol RepoListViewInterface: ViewInterface {
    func displayListOfRepos(_ viewModel: [RepoListItemViewModel])
}

protocol RepoListPresenterInterfaceInput: PresenterInterface {

    var isLoading: Bool {get set}
    var defaultRows: Int {get set}
    var title: String {get set}
    
    func viewLoaded()
}

protocol RepoListPresenterInterfaceOutput: PresenterInterface {
    func presentListOfRepos(_ model: APIRepoListModel)
    
}

protocol RepoListInteractorInterface: InteractorInterface {
    var presenter: RepoListPresenterInterfaceOutput? { get set }
    
    func getRepositories()
}
